/** Desafios do Faz ou Bebe — níveis leve / médio / pesado */
window.CHALLENGES = {
  faz: {
    leve: [
      "Imite a pessoa à sua esquerda por 20 segundos.",
      "Conte a pior piada que você conhece. Se ninguém rir, bebe 1 gole.",
      "Fale com sotaque carioca até a próxima rodada.",
      "Mande um áudio constrangedor pra alguém da roda (com permissão).",
      "Dance por 15 segundos sem música.",
      "Troque de lugar com quem estiver na sua frente.",
      "Fale 3 qualidades da pessoa à sua direita.",
      "Faça uma cara de sério e tente não rir por 20 segundos enquanto a galera provoca.",
      "Conte um fato aleatório e inútil sobre você.",
      "Cante o refrão de uma música escolhida pela mesa.",
      "Fale só em perguntas até a próxima vez que jogar.",
      "Invente um apelido novo pra cada pessoa da mesa.",
      "Faça uma declaração dramática de amizade pra alguém.",
      "Mime um filme e deixe a galera adivinhar (1 minuto).",
      "Poste (ou mostre no grupo) a última foto da sua galeria — sem abrir pasta íntima.",
      "Conte a história mais vergonhosa da escola (leve).",
      "Imite um apresentador de TV anunciando a próxima rodada.",
      "Faça 10 polichinelos agora.",
      "Deixe alguém da mesa controlar seu celular por 30 segundos (só tela atual).",
      "Escolha alguém pra te dar um desafio leve inventado na hora.",
    ],
    medio: [
      "Ligue pra alguém e diga: “tô só testando o celular”. Desligue em 5 segundos.",
      "Mostre o último status que você visualizou (se tiver).",
      "Conte um crush antigo da galera — sem falar o nome… ou bebe 2.",
      "Deixe a mesa escolher uma música e dance até o fim do refrão.",
      "Fale um segredo que quase ninguém sabe — pode ser besta.",
      "Troque uma peça de roupa acessória com alguém (boné, pulseira, etc).",
      "Faça um elogio exagerado e constrangedor pra pessoa à esquerda.",
      "Imite o jeito de flertar de alguém da mesa.",
      "Conte a última vez que você ficou sem graça em público.",
      "Deixe a galera ler em voz alta a última mensagem que você mandou (não íntima).",
      "Fale “eu te amo” olhando nos olhos de alguém da mesa — e segure 5 segundos.",
      "Invente uma mentira absurda sobre você e defenda por 30 segundos.",
      "Faça uma pose de capa de revista e tire foto.",
      "Escolha alguém pra te maquiar com o que tiver na mesa (batom, caneta…).",
      "Reaja a um áudio aleatório do grupo como se fosse uma novela.",
      "Conte quem da mesa você acha que seria o pior colega de quarto.",
      "Fale com voz de bebê até a próxima rodada — ou bebe 2.",
      "Deixe a mesa montar uma bio do Instagram pra você e leia em voz alta.",
      "Descreva seu tipo ideal sem usar a palavra “pessoa”.",
      "Faça uma declaração falsa de término pra alguém da mesa (teatro).",
    ],
    pesado: [
      "Conte o momento mais constrangedor da sua vida amorosa.",
      "Mostre a conversa mais antiga que ainda tá aberta no WhatsApp.",
      "Deixe a mesa fazer 3 perguntas sinceras — você responde ou bebe 3.",
      "Ligue pra um ex/crush (se todos toparem o clima) e diga só “foi mal, errei o número”.",
      "Revele quem da mesa você acharia mais difícil de morar junto — e por quê.",
      "Imite como seria o seu flerte bêbado — versão completa.",
      "Conte um “quase aconteceu” da sua vida que quase ninguém sabe.",
      "Deixe alguém da mesa escolher uma foto sua pra postar no status por 10 min.",
      "Fale o nome de alguém que você já gostou em silêncio nesta mesa.",
      "Troque de camisa/blusa com alguém da mesa (só se ambos toparem).",
      "Faça uma lista ranqueada: quem da mesa é mais confuso em relacionamento.",
      "Conte a pior mensagem que você já mandou bêbado.",
      "Deixe a galera inventar um challenge absurdo e você executa em 1 minuto.",
      "Leia em voz alta a última pesquisa do Google no celular (sem abrir pastas).",
      "Descreva seu pior date em detalhes — sem poupar ninguém.",
      "Escolha alguém e diga 2 verdades e 1 mentira sobre o que você acha dessa pessoa.",
      "Fique de quatro e late por 10 segundos — ou bebe 3.",
      "Conte quem você acha que fica com quem nesta mesa (só opinião, leve).",
      "Mande um áudio cantando “Parabéns pra Você” pra um contato aleatório.",
      "Responda: qual foi a coisa mais ousada que você já fez numa festa?",
    ],
  },
  bebe: {
    leve: [
      "Bebe 1 gole.",
      "Bebe 2 goles.",
      "Quem riu por último bebe com você — 1 gole cada.",
      "Bebe 1 e escolha alguém pra beber junto.",
      "Bebe enquanto a galera conta até 5.",
      "Faça um brinde dramático e beba 1.",
      "Bebe 1 se você já mandou mensagem errada hoje.",
      "Todos que estiverem de preto bebem 1 — incluindo você se for o caso.",
      "Bebe 1 e diga “saúde, mesa!” bem alto.",
      "Troca: você bebe 1 ou a pessoa à direita bebe 2.",
      "Bebe 1 sem usar as mãos (cuidado).",
      "Quem tiver o copo mais cheio bebe 1 com você.",
      "Bebe 1 a cada pessoa da mesa com o mesmo signo que você (mín. 1).",
      "Role um “valeu” coletivo: todos bebem 1, você bebe 2.",
      "Bebe 1 e invente um toast constrangedor.",
    ],
    medio: [
      "Bebe 3 goles.",
      "Bebe 2 e escolha 2 pessoas pra beber 1 cada.",
      "Bebe enquanto canta o hino (ou trecho) — para quando errar.",
      "Você e a pessoa à esquerda: quem perder no par ou ímpar bebe 2.",
      "Bebe 2 se já gostou de alguém da mesa. Se negar, a mesa decide se acredita.",
      "Faça um shot (ou 3 goles) olhando nos olhos de alguém.",
      "Bebe 2 e fale um segredo besta. Se for bom, a mesa bebe 1.",
      "Todos bebem 1; você bebe 3.",
      "Bebe 2 de costas. Se derramar, bebe mais 1.",
      "Escolha: bebe 3 agora ou 1 a cada rodada pelas próximas 3.",
      "Bebe 2 e dê um apelido pra noite.",
      "Quem você apontar bebe 2 — mas você bebe 1 junto.",
      "Bebe no ritmo de uma música por 8 segundos.",
      "Faça um brinde em outro idioma e beba 2.",
      "Bebe 3 se já fingiu que tava bem numa festa. Senão, bebe 1.",
    ],
    pesado: [
      "Bebe 4 goles. Sem drama.",
      "Shot (ou 4 goles) + escolha alguém pra dobrar com você.",
      "Bebe até a galera parar de bater palma (máx. 8 segundos).",
      "Você bebe 3; a pessoa que você menos conhece na mesa bebe 2.",
      "Desafio da mesa: eles inventam uma regra e você bebe 3 se quebrar nas próximas 2 rodadas.",
      "Bebe 3 e conte algo que normalmente não contaria sóbrio — ou bebe +2.",
      "Todos apontam pra quem “merece” beber: quem tiver mais votos bebe 3; você bebe 2.",
      "Bebe 4 se já mandou mensagem arrependida pra crush. Senão, bebe 2 mesmo assim.",
      "Faça um toast sincero e beba 3.",
      "Roleta: a mesa escolhe entre 2 ou 5 goles pra você.",
      "Bebe 3 sem respirar no meio (com segurança).",
      "Você e outra pessoa: quem rir primeiro bebe 3.",
      "Bebe 2 agora e 2 na próxima vez que falar.",
      "Final boss: bebe 5 ou faz o desafio FAZ mais pesado que a mesa inventar.",
      "Bebe 4 e passe o próximo desafio pra quem você quiser.",
    ],
  },
};
